# Generated by Django 5.1.4 on 2025-12-05 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_badge_challenge_activitylog_teambadge_team_badges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
